USE eklhad;

INSERT INTO `links` VALUES (21,'[SCPR] Comedy Hack Day brings comedians and programmers together in Los Angeles','2014-12-06','press','http://www.scpr.org/blogs/newmedia/2014/12/06/17651/comedy-hack-day-brings-comedians-and-programmers-t/'),
	(25,'[ODBMS] Powering Big Data at Pinterest. Interview with Krishna Gade.','2015-04-22','press','http://www.odbms.org/blog/2015/04/powering-big-data-at-pinterest-interview-with-krishna-gade/'),
	(7,'Exploring Wikipedia Using MemSQL','2015-05-07','demo','https://www.youtube.com/watch?v=bgXbHL3D3vs'),
	(29,'[DePaul University] Computer Science Program Discussion','2012-03-09','press','http://www.depaul.edu/academics/undergraduate/majors/Pages/comp-sci.aspx'),
	(15,'Setting up Sublime Text 3 from the Command Line','2013-11-23','blog','https://gist.github.com/dahlke/7330342'),
	(8,'MemSQL Supercar Real-Time Geospatial Demo','2015-04-13','demo','https://www.youtube.com/watch?v=2txICCLUV-Y'),
	(24,'[Medium] Furby does Python - The soul of a furry machine: Scenes from a comedy hackathon','2014-10-09','press','https://backchannel.com/furby-does-python-1b68297d1d26#.c2u8zkwbm'),
	(4,'TaxiStats Showcase Application','2016-02-22','demo','https://www.youtube.com/watch?v=26lfq_qgcRI'),
	(10,'MemSQL, Tableau, and the Democratization of Data','2016-11-10','blog','http://blog.memsql.com/memsql-tableau-and-the-democratization-of-data/'),
	(3,'Election 2016: Real-Time Twitter Analytics','2016-10-18','demo','http://election.memsql.com'),
	(26,'[InfoQ] Real-time Data Analytics at Pinterest using MemSQL and Spark Streaming','2015-03-29','press','https://www.infoq.com/news/2015/03/pinterest-memsql-spark-streaming'),
	(1,'MemSQL Roadshow Phoenix: Real-Time Analytics with MemSQL and Spark','2016-11-04','talk','http://www1.memsql.com/phoenix-roadshow.html'),
	(30,'MemSQL Roadshow Orange County: Real-Time Analytics with MemSQL and Spark','2017-03-17','talk','http://www1.memsql.com/ocroadshow.html'),
	(18,'jQuery Conference Austin','2013-09-10','blog','https://gist.github.com/dahlke/6509891'),
	(9,'Comedy Hack Day - AwwCog','2014-10-06','demo','http://www.comedyhackday.org/demosmade/2014/10/6/wearable-furby'),
	(14,'WhoJS Tutorial','2013-08-09','blog','https://gist.github.com/dahlke/7ce2ea3e476c04aa7ef7'),
	(28,'[GigaOm] Pinterest is experimenting with MemSQL for real-time data analytics','2015-02-18','press','https://gigaom.com/2015/02/18/pinterest-is-experimenting-with-memsql-for-real-time-data-analytics/'),
	(13,'The Internet of Furbies','2014-10-01','blog','http://blog.memsql.com/the-internet-of-furbies/'),
	(23,'[Engadget] Dev comedy jam: Cultivated Wit\'s Hack Day chases laughs, not dollars','2016-10-10','press','https://www.engadget.com/2014/10/10/comedy-hack-day/'),
	(20,'[Silicon Angle] Real-time Twitter analysis shows U.S. election is … too close to call?','2016-10-21','press','http://siliconangle.com/blog/2016/10/21/real-time-twitter-analysis-shows-election-is-too-close-to-call/'),
	(5,'Pinterest Demo of Spark Connector','2015-06-17','demo','https://www.youtube.com/watch?v=KXelkQFVz4E'),
	(27,'[Pinterest Engineering Blog] Real-time analytics at Pinterest','2015-02-18','press','https://engineering.pinterest.com/blog/real-time-analytics-pinterest'),
	(2,'Geospatial Data Meetup with Mapbox','2016-06-29','talk','http://blog.memsql.com/geospatial-data-meetup-with-mapbox/'),
	(12,'How Pinterest Measures Real-Time User Engagement with Spark','2015-02-18','blog','http://blog.memsql.com/pinterest-apache-spark-use-case/'),
	(22,'[ReCode] Wearable Furbys and On-Demand High Fives Highlight Comedy Hack Day','2014-10-11','press','http://www.recode.net/2014/10/11/11631780/wearable-furbys-and-on-demand-high-fives-highlight-comedy-hack-day'),
	(6,'Bringing OLAP Fully Online: Analyze Changing Datasets in MemSQL and Spark with Pinterest Demo w/ Eric Frenkiel','2015-05-08','demo','https://www.youtube.com/watch?v=5_0rG5GhHNE'),
	(16,'Workshop: Wireframing Tools and Techniques w/ Carolyn Chandler','2013-11-14','blog','https://gist.github.com/dahlke/7452852'),
	(19,'[Datanami] 8 Interactive Visualizations for Election Day','2016-11-07','press','https://www.datanami.com/2016/11/07/8-visualizations-election-day/'),
	(11,'Election 2016: Analyzing Real-Time Twitter Sentiment with MemSQL Pipelines','2016-10-18','blog','http://blog.memsql.com/election-2016-real-time-twitter-sentiment/'),
	(17,'Setting up a Raspberry Pi web server using Node & Express','2013-11-05','blog','https://gist.github.com/dahlke/7330365'),
	(31,'Radiant Advisors Presents: MemSQL, Real Time Data Warehousing in the Hybrid Cloud','2017-06-14','talk','http://radiantadvisors.com/'),
	(32,'Kafka Summit in New York, Using MemSQL and Kafka','2017-05-08','talk','https://kafka-summit.org/events/kafka-summit-ny/'),
	(33,'MissionBit Student Panel','2017-07-07','talk','http://www.missionbit.com/'),
	(34,'MemSQL San Francisco Roadshow: Streaming in the Enterprise with MemSQL','2017-06-15','talk','http://www1.memsql.com/sf-roadshow-2017.html'),
	(35,'Real-Time Streaming, Analytics, and Visualization with MemSQL and Zoomdata','2017-08-10','talk','https://www.meetup.com/MemSQL/events/241801222/'),
	(36,'Gartner Catalyst Conference: Image Recognition on Streaming Data','2017-08-20','talk','https://www.slideshare.net/MemSQL/image-recognition-on-streaming-data'),
	(37,'AWS Re:Invent - Machine Learning and Streaming Data','2017-11-29','talk','https://reinvent.awsevents.com/'),
	(38,'Real-Time Streaming, Analytics, and Visualization With MemSQL and Zoomdata','2017-11-24','press','https://dzone.com/articles/real-time-streaming-analytics-and-visualization-wi');
