aws_region = "us-west-1"
aws_zone = "us-west-1b"
aws_machine_type = "t3.micro"
ssh_user = "ubuntu"
local_ssh_public_key_path = "~/.ssh/eklhad-web-aws.pub"
local_ssh_private_key_path = "~/.ssh/eklhad-web-aws"
cloudflare_zone_id = "a70fcfded631f4a054a2876f0a262f7a"
email = "neil@dahlke.io"
