version: 2.1
commands:
  gcp_auth:
    steps:
      - run: touch $GOOGLE_APPLICATION_CREDENTIALS
      - run: echo $GOOGLE_ACTIONS_CREDENTIALS_JSON > $GOOGLE_APPLICATION_CREDENTIALS
jobs:
  go_js_test:
    docker:
      - image: eklhad/eklhad-web-circleci:0.1.2
    working_directory: /go/src/github.com/dahlke/eklhad/
    steps:
      - checkout
      - gcp_auth
      - run: make go_get
      - run: make go_test
      - run: npm --prefix web/frontend/ install
      - run: npm --prefix web/frontend/ run-script test-once
  data_workers:
    docker:
      - image: eklhad/eklhad-web-circleci:0.1.2
    working_directory: /go/src/github.com/dahlke/eklhad/
    steps:
      - checkout
      - gcp_auth
      - run: make go_get
      - run: make go_test
      - run: make collect_data
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - go_js_test
      - data_workers:
          requires:
            - go_js_test
          filters:
            branches:
              only: main
  data_workers:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - data_workers
