version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9-node
    working_directory: /go/src/github.com/dahlke/eklhad/
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: npm --prefix web/frontend/ install
      - run: npm --prefix web/frontend/ run-script test